server.port=8085
spring.application.name=report-service

# Eureka Client
eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka/
eureka.instance.prefer-ip-address=true

# External Service URLs
nic-service.url=http://127.0.0.1:8083
